import bcrypt from 'bcryptjs';
import { PrismaClient, type Prisma } from '@prisma/client';

const prisma = new PrismaClient();

const DEMO_EMAIL = 'admin';
const DEMO_PASSWORD = 'admin';
const TASK_INSERT_CHUNK_SIZE = 60;

type SeedMode = 'basic' | 'stress';
type StressDatasetMode = 'single' | 'ten' | 'many' | 'all';

type StressListConfig = {
  title: string;
  taskCount: number;
};

type DemoTaskConfig = {
  title: string;
  description: string | null;
  status: number;
  priority: number;
  startDate?: Date | null;
  deadline?: Date | null;
};

type DemoListConfig = {
  title: string;
  tasks: DemoTaskConfig[];
};

const seedMode: SeedMode =
  process.env.SEED_MODE === 'stress' ? 'stress' : 'basic';

const stressDatasetMode: StressDatasetMode = (() => {
  switch (process.env.STRESS_DATASET) {
    case 'single':
    case 'ten':
    case 'many':
      return process.env.STRESS_DATASET;
    default:
      return 'all';
  }
})();

const buildTaskTitle = (taskIndex: number): string => {
  const id = taskIndex + 1;
  if (taskIndex % 3 === 0) {
    return `Task ${id}: quick follow-up`;
  }
  if (taskIndex % 3 === 1) {
    return `Task ${id}: verify details for release checklist and prepare next action`;
  }
  return `Task ${id}: coordinate cross-team updates, document progress, and confirm acceptance criteria before moving the card to completed state`;
};

const buildTaskDescription = (taskIndex: number): string | null => {
  if (taskIndex % 5 !== 0) return null;
  return `Autogenerated stress item #${taskIndex + 1} for responsive and layout checks.`;
};

const createRelativeDate = (daysOffset: number, hour: number): Date => {
  const date = new Date();

  date.setDate(date.getDate() + daysOffset);
  date.setHours(hour, 0, 0, 0);

  return date;
};

const basicLists: DemoListConfig[] = [
  {
    title: 'Product launch',
    tasks: [
      {
        title: 'Finalize release notes',
        description:
          'Collect changes from frontend and backend and prepare the public changelog.',
        status: 1,
        priority: 3,
        startDate: createRelativeDate(-1, 10),
        deadline: createRelativeDate(1, 18),
      },
      {
        title: 'Confirm production env variables',
        description:
          'Verify API URL, JWT secret rotation plan, and allowed frontend origins before deployment.',
        status: 0,
        priority: 4,
        startDate: createRelativeDate(0, 9),
        deadline: createRelativeDate(2, 12),
      },
      {
        title: 'Record demo walkthrough',
        description:
          'Capture a short product video with authentication, list filtering, and task updates.',
        status: 3,
        priority: 2,
      },
      {
        title: 'Publish release announcement',
        description:
          'Share the release note link with the team and early users.',
        status: 2,
        priority: 1,
      },
    ],
  },
  {
    title: 'Client support',
    tasks: [
      {
        title: 'Reply to onboarding questions',
        description:
          'Answer the latest questions from the pilot customer about login and task statuses.',
        status: 0,
        priority: 2,
        deadline: createRelativeDate(1, 15),
      },
      {
        title: 'Review bug report from beta user',
        description:
          'Reproduce the issue around editing task titles on mobile and attach findings.',
        status: 1,
        priority: 3,
        startDate: createRelativeDate(-2, 11),
      },
      {
        title: 'Prepare FAQ follow-up',
        description:
          'Turn the most frequent setup questions into a concise FAQ entry.',
        status: 2,
        priority: 1,
      },
    ],
  },
  {
    title: 'Personal',
    tasks: [
      {
        title: 'Buy groceries for the week',
        description: 'Vegetables, yogurt, coffee beans, and sparkling water.',
        status: 0,
        priority: 1,
        deadline: createRelativeDate(0, 20),
      },
      {
        title: 'Book annual health check',
        description:
          'Find a morning appointment that does not conflict with sprint planning.',
        status: 1,
        priority: 2,
        startDate: createRelativeDate(-3, 9),
      },
      {
        title: 'Call parents on Sunday',
        description: null,
        status: 2,
        priority: 0,
      },
      {
        title: 'Plan weekend trip',
        description: 'Pick a route, budget, and one cafe to visit on the way.',
        status: 3,
        priority: 1,
      },
    ],
  },
  {
    title: 'Learning backlog',
    tasks: [
      {
        title: 'Finish Prisma migration notes',
        description:
          'Document the migration workflow for local, staging, and production environments.',
        status: 1,
        priority: 2,
        startDate: createRelativeDate(-4, 14),
      },
      {
        title: 'Read about structured logging',
        description:
          'Compare JSON logs, request correlation, and masking strategies for auth events.',
        status: 0,
        priority: 1,
      },
      {
        title: 'Practice integration test cases',
        description:
          'Add scenarios for auth expiration, malformed JSON, and ownership boundaries.',
        status: 0,
        priority: 3,
        deadline: createRelativeDate(3, 17),
      },
      {
        title: 'Archive finished notes',
        description: null,
        status: 2,
        priority: 0,
      },
    ],
  },
];

const buildStressLists = (dataset: StressDatasetMode): StressListConfig[] => {
  const singleList: StressListConfig[] = [
    {
      title: 'Stress: Single massive list (300 tasks)',
      taskCount: 300,
    },
  ];

  const tenHeavyLists: StressListConfig[] = Array.from(
    { length: 10 },
    (_, index) => ({
      title: `Stress: Team queue #${index + 1}`,
      taskCount: 80,
    }),
  );

  const manyLists: StressListConfig[] = Array.from(
    { length: 30 },
    (_, index) => ({
      title: `Stress: Compact board #${index + 1}`,
      taskCount: 30,
    }),
  );

  switch (dataset) {
    case 'single':
      return singleList;
    case 'ten':
      return tenHeavyLists;
    case 'many':
      return manyLists;
    case 'all':
    default:
      return [...singleList, ...tenHeavyLists, ...manyLists];
  }
};

const clearUserData = async (userId: number) => {
  await prisma.task.deleteMany({
    where: {
      todolist: {
        userId,
      },
    },
  });

  await prisma.todolist.deleteMany({
    where: { userId },
  });
};

const createTasksInChunks = async (data: Prisma.TaskCreateManyInput[]) => {
  for (let index = 0; index < data.length; index += TASK_INSERT_CHUNK_SIZE) {
    await prisma.task.createMany({
      data: data.slice(index, index + TASK_INSERT_CHUNK_SIZE),
    });
  }
};

const seedBasicLists = async (userId: number) => {
  let totalTasks = 0;

  for (let listIndex = 0; listIndex < basicLists.length; listIndex += 1) {
    const listConfig = basicLists[listIndex];
    const createdList = await prisma.todolist.create({
      data: {
        title: listConfig.title,
        order: listIndex,
        userId,
      },
    });

    await prisma.task.createMany({
      data: listConfig.tasks.map((task, taskIndex) => ({
        title: task.title,
        description: task.description,
        status: task.status,
        priority: task.priority,
        order: taskIndex,
        startDate: task.startDate ?? null,
        deadline: task.deadline ?? null,
        todoListId: createdList.id,
      })),
    });

    totalTasks += listConfig.tasks.length;
  }

  return {
    totalLists: basicLists.length,
    totalTasks,
  };
};

const seedStressLists = async (userId: number, dataset: StressDatasetMode) => {
  const lists = buildStressLists(dataset);

  let totalTasks = 0;
  for (let listIndex = 0; listIndex < lists.length; listIndex += 1) {
    const listConfig = lists[listIndex];
    const createdList = await prisma.todolist.create({
      data: {
        userId,
        title: listConfig.title,
        order: listIndex,
      },
    });

    const tasks: Prisma.TaskCreateManyInput[] = Array.from(
      { length: listConfig.taskCount },
      (_, taskIndex) => ({
        title: buildTaskTitle(taskIndex),
        description: buildTaskDescription(taskIndex),
        status: taskIndex % 4,
        priority: taskIndex % 5,
        order: taskIndex,
        startDate: null,
        deadline: null,
        todoListId: createdList.id,
      }),
    );

    await createTasksInChunks(tasks);
    totalTasks += listConfig.taskCount;
  }

  return {
    totalLists: lists.length,
    totalTasks,
  };
};

async function main() {
  const passwordHash = await bcrypt.hash(DEMO_PASSWORD, 10);

  const user = await prisma.user.upsert({
    where: { email: DEMO_EMAIL },
    create: {
      email: DEMO_EMAIL,
      login: 'admin',
      passwordHash,
    },
    update: {
      login: 'admin',
      passwordHash,
    },
  });

  await clearUserData(user.id);

  if (seedMode === 'stress') {
    const result = await seedStressLists(user.id, stressDatasetMode);
    console.log(
      `Stress seed complete: dataset=${stressDatasetMode}, lists=${result.totalLists}, tasks=${result.totalTasks}`,
    );
  } else {
    const result = await seedBasicLists(user.id);
    console.log(
      `Basic seed complete: lists=${result.totalLists}, tasks=${result.totalTasks}`,
    );
  }

  console.log(`Demo credentials: ${DEMO_EMAIL} / ${DEMO_PASSWORD}`);
}

main()
  .catch(error => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
