import bcrypt from 'bcryptjs';
import { PrismaClient, type Prisma } from '@prisma/client';

const prisma = new PrismaClient();

const DEMO_EMAIL = 'admin';
const DEMO_PASSWORD = 'admin';
const TASK_INSERT_CHUNK_SIZE = 60;

type SeedMode = 'basic' | 'stress';
type StressDatasetMode = 'single' | 'ten' | 'many' | 'all';

type StressListConfig = {
  title: string;
  taskCount: number;
};

const seedMode: SeedMode =
  process.env.SEED_MODE === 'stress' ? 'stress' : 'basic';

const stressDatasetMode: StressDatasetMode = (() => {
  switch (process.env.STRESS_DATASET) {
    case 'single':
    case 'ten':
    case 'many':
      return process.env.STRESS_DATASET;
    default:
      return 'all';
  }
})();

const rangeValue = (
  index: number,
  min: number,
  max: number,
  salt = 11,
): number => {
  const span = max - min + 1;
  return min + ((index * salt + 17) % span);
};

const buildTaskTitle = (taskIndex: number): string => {
  const id = taskIndex + 1;
  if (taskIndex % 3 === 0) {
    return `Task ${id}: quick follow-up`;
  }
  if (taskIndex % 3 === 1) {
    return `Task ${id}: verify details for release checklist and prepare next action`;
  }
  return `Task ${id}: coordinate cross-team updates, document progress, and confirm acceptance criteria before moving the card to completed state`;
};

const buildTaskDescription = (taskIndex: number): string | null => {
  if (taskIndex % 5 !== 0) return null;
  return `Autogenerated stress item #${taskIndex + 1} for responsive and layout checks.`;
};

const buildStressLists = (dataset: StressDatasetMode): StressListConfig[] => {
  const singleList: StressListConfig[] = [
    {
      title: 'Stress: Single massive list (320 tasks)',
      taskCount: 320,
    },
  ];

  const tenHeavyLists: StressListConfig[] = Array.from(
    { length: 10 },
    (_, index) => ({
      title: `Stress: Team queue #${index + 1}`,
      taskCount: rangeValue(index, 50, 100, 19),
    }),
  );

  const manyLists: StressListConfig[] = Array.from(
    { length: 40 },
    (_, index) => ({
      title: `Stress: Compact board #${index + 1}`,
      taskCount: rangeValue(index, 10, 30, 7),
    }),
  );

  switch (dataset) {
    case 'single':
      return singleList;
    case 'ten':
      return tenHeavyLists;
    case 'many':
      return manyLists;
    case 'all':
    default:
      return [...singleList, ...tenHeavyLists, ...manyLists];
  }
};

const clearUserData = async (userId: number) => {
  await prisma.task.deleteMany({
    where: {
      todolist: {
        userId,
      },
    },
  });

  await prisma.todolist.deleteMany({
    where: { userId },
  });
};

const createTasksInChunks = async (data: Prisma.TaskCreateManyInput[]) => {
  for (let index = 0; index < data.length; index += TASK_INSERT_CHUNK_SIZE) {
    await prisma.task.createMany({
      data: data.slice(index, index + TASK_INSERT_CHUNK_SIZE),
    });
  }
};

const seedBasicLists = async (userId: number) => {
  const workList = await prisma.todolist.create({
    data: {
      title: 'Work',
      order: 0,
      userId,
    },
  });

  const personalList = await prisma.todolist.create({
    data: {
      title: 'Personal',
      order: 1,
      userId,
    },
  });

  await prisma.task.createMany({
    data: [
      {
        title: 'Prepare sprint plan',
        description: 'Review backlog and estimate tasks',
        status: 0,
        priority: 2,
        order: 0,
        todoListId: workList.id,
      },
      {
        title: 'Finish API integration',
        description: 'Connect frontend to local backend',
        status: 1,
        priority: 3,
        order: 1,
        todoListId: workList.id,
      },
      {
        title: 'Buy groceries',
        description: null,
        status: 0,
        priority: 0,
        order: 0,
        todoListId: personalList.id,
      },
      {
        title: 'Read 20 pages',
        description: null,
        status: 2,
        priority: 1,
        order: 1,
        todoListId: personalList.id,
      },
    ],
  });
};

const seedStressLists = async (userId: number, dataset: StressDatasetMode) => {
  const lists = buildStressLists(dataset);

  let totalTasks = 0;
  for (let listIndex = 0; listIndex < lists.length; listIndex += 1) {
    const listConfig = lists[listIndex];
    const createdList = await prisma.todolist.create({
      data: {
        userId,
        title: listConfig.title,
        order: listIndex,
      },
    });

    const tasks: Prisma.TaskCreateManyInput[] = Array.from(
      { length: listConfig.taskCount },
      (_, taskIndex) => ({
        title: buildTaskTitle(taskIndex),
        description: buildTaskDescription(taskIndex),
        status: taskIndex % 4,
        priority: taskIndex % 5,
        order: taskIndex,
        startDate: null,
        deadline: null,
        todoListId: createdList.id,
      }),
    );

    await createTasksInChunks(tasks);
    totalTasks += listConfig.taskCount;
  }

  return {
    totalLists: lists.length,
    totalTasks,
  };
};

async function main() {
  const passwordHash = await bcrypt.hash(DEMO_PASSWORD, 10);

  const user = await prisma.user.upsert({
    where: { email: DEMO_EMAIL },
    create: {
      email: DEMO_EMAIL,
      login: 'admin',
      passwordHash,
    },
    update: {
      login: 'admin',
      passwordHash,
    },
  });

  await clearUserData(user.id);

  if (seedMode === 'stress') {
    const result = await seedStressLists(user.id, stressDatasetMode);
    console.log(
      `Stress seed complete: dataset=${stressDatasetMode}, lists=${result.totalLists}, tasks=${result.totalTasks}`,
    );
  } else {
    await seedBasicLists(user.id);
    console.log('Basic seed complete');
  }

  console.log(`Demo credentials: ${DEMO_EMAIL} / ${DEMO_PASSWORD}`);
}

main()
  .catch(error => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
